# Generated by Django 5.0.7 on 2024-08-05 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flower',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Каталог'},
        ),
        migrations.AlterField(
            model_name='flower',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='flower',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='catalog/images/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='flower',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='flower',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
    ]
